- action:
  - service: script.light_plants_on
  alias: turn_on_light_plants
  condition: []
  id: '1518642425834'
  trigger:
  - event: sunrise
    platform: sun
- action:
  - service: script.light_plants_off
  alias: turn_off_light_plants
  condition: []
  id: '1518642622398'
  trigger:
  - at: '23:00:00'
    platform: time

# # REFRESH OWNTRACKS #
# - id: '1518642622399'
  # alias: refresh_owntracks
  # trigger:
    # - platform: time
      # minutes: '/5'
      # seconds: 00
  # action:
    # - service: mqtt.publish
      # data:
        # topic: "owntracks/mqtt/galaxys7/cmd"
        # payload_template: '{"_type": "cmd","action": "reportlocation"}'
