- action:
  - service: script.light_plants_on
  alias: turn_on_light_plants
  condition: []
  id: '001'
  trigger:
  - event: sunrise
    platform: sun
- action:
  - service: script.light_plants_off
  alias: turn_off_light_plants
  condition: []
  id: '002'
  trigger:
  - at: '23:00:00'
    platform: time

# REFRESH OWNTRACKS #
# - id: '1518642622399'
  # alias: refresh_owntracks
  # trigger:
    # - platform: time
      # minutes: '/5'
      # seconds: 00
  # action:
    # - service: mqtt.publish
      # data:
        # topic: "owntracks/polina/iphone/cmd"
        # payload_template: '{"_type": "cmd","action": "reportLocation"}'

# - id: '003'
  # alias: icloud_update
  # trigger:
    # - platform: time
      # minutes: '/5'
      # seconds: 00
  # action:
    # - service: device_tracker.icloud_update