# автоматизация подсветки растений -------------------

- id: turn_on_light_plants
  alias: turn_on_light_plants
  action:
  - service: script.light_plants_on
  condition: []
  trigger:
  - platform: template
    value_template: "{{ states.sensor.time.state == states.input_datetime.turn_on_light_plants.state[0:5] }}"
- id: turn_off_light_plants
  alias: turn_off_light_plants
  action:
  - service: script.light_plants_off
  condition: []
  trigger:
  - platform: template
    value_template: "{{ states.sensor.time.state == states.input_datetime.turn_off_light_plants.state[0:5] }}"
 
 # полив растений -------
 
- id: turn_on_autowatering
  alias: turn_on_autowatering
  action:
  - service: script.start_autowatering
    data:
      entity_id: switch.autowatering
  trigger:
  - platform: template
    value_template: "{{ (as_timestamp(now()) - as_timestamp(states.input_datetime.last_autowatering.state)) /3600 > (states.input_number.autowatering_interval.state | int)}}"
 
 # автоматизация теплого пола ----------------------
 
- id: turn_on_warm_flow_morning
  alias: turn_on_warm_flow_morning
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.hall_warmfloor
  trigger:
  - platform: template
    value_template: "{{ states.sensor.time.state == states.input_datetime.turn_on_warm_flow_morning.state[0:5] }}"
  condition:
  - condition: state
    entity_id: group.all_devices
    state: home
    
- id: turn_off_warm_flow_day
  alias: turn_off_warm_flow_day
  trigger:
  - platform: template
    value_template: >
      {{ states.sensor.time.state == states.input_datetime.turn_off_warm_flow_day.state[0:5] 
      or states.sensor.time.state == states.input_datetime.turn_off_warm_flow_day2.state[0:5] 
      }}
  condition:
  - condition: state
    entity_id: group.all_devices
    state: not_home
  action:
  - data:
      entity_id: switch.hall_warmfloor
    service: switch.turn_off
    
- id: turn_on_warm_flow_evening
  alias: turn_on_warm_flow_evening
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.hall_warmfloor
  trigger:
  - platform: template
    value_template: "{{ states.sensor.time.state == states.input_datetime.turn_on_warm_flow_evening.state[0:5] }}"
    
- id: turn_off_warm_flow_night
  alias: turn_off_warm_flow_night
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.hall_warmfloor
  trigger:
  - platform: template
    value_template: "{{ states.sensor.time.state == states.input_datetime.turn_off_warm_flow_night.state[0:5] }}"
 
 # --------------
 
- id: test1
  trigger:
    platform: webhook
    webhook_id: test
  action:
    service: logbook.log
    data_template:
      name: testlog
      message: >
        {{ trigger.data.a }}
        
- id: mqtt_started
  trigger:
    platform: mqtt
    topic: Start
  action:
    service: logbook.log
    data_template:
      name: started
      message: >
        {{ trigger.payload }}