- id: turn_on_light_plants  
  alias: Включить подсветку растений
  trigger:
    platform: sun
    event: sunrise
  action:
    service: script.light_plants_on

- id: turn_off_light_plants  
  alias: Выключить подсветку растений
  trigger:
    platform: time
    at: "23:00:00"
  action:
    service: script.light_plants_off
