homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 123
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Moscow
  
  customize: !include customize.yaml
  
  auth_providers:
   - type: homeassistant
   - type: legacy_api_password
   - type: trusted_networks

group: !include groups.yaml
script: !include scripts.yaml
automation: !include automations.yaml
intent_script: !include intent_scripts.yaml
zone: !include zones.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  trusted_networks:
    - 192.168.88.0/24

  

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

device_tracker:
  - platform: snmp
    host: 192.168.88.1
    community: !secret snmp_comunity 
    baseoid: 1.3.6.1.4.1.14988.1.1.1.2.1.1
    track_new_devices: false
    interval_seconds: 30
    home_interval: 5
    consider_home: 120
  - platform: icloud
    username: polinaizm3004@gmail.com
    password: !secret polina_icloud_password
    filter_devices: 'phone'
  # - platform: owntracks
    # mqtt_topic: "owntracks"
  - platform: gpslogger
    password: !secret gpslogger_password
  # - platform: google_maps
    # username: rodal2807.home@gmail.com
    # password: !secret google_password

# Weather Prediction
sensor:
  - platform: yr
  
  - platform: mqtt
    state_topic: 'home/dht/1'
    name: temperature
    unit_of_measurement: '°C'
    value_template: '{{ value_json.temperature }}'
    
  - platform: mqtt
    state_topic: 'home/dht/1'
    name: humidity
    unit_of_measurement: '%'
    value_template: '{{ value_json.humidity }}'
        
  # - platform: filter
    # name: "filtered humidity"
    # entity_id: sensor.Humidity
    # filters:
      # - filter: outlier
        # window_size: 4
        # radius: 4.0
      # - filter: lowpass
        # time_constant: 10
        # precision: 2    
#  - platform: openweathermap
#    api_key: !secret openweather_apikey
#    monitored_conditions:
#      - weather
#      - temperature
#      - wind_speed
#      - humidity
#      - clouds
#      - rain
#      - snow

light:
# подсветка кухни
  - platform: mqtt
    name: switch3
    state_topic: "home/switches/switch3/pins/14/state"
    command_topic: "home/switches/switch3/pins/14"
    payload_on: 1
    payload_off: 0
    qos: 0
# лампа на кухне
  - platform: mqtt
    name: switch2_main
    state_topic: "home/switches/switch2/pins/14/state"
    command_topic: "home/switches/switch2/pins/14"
    payload_on: 1
    payload_off: 0
    qos: 0
# свет в ванной
  - platform: mqtt
    name: switch4
    state_topic: "home/switches/4/status"
    command_topic: "home/switches/4"
    payload_on: 1
    payload_off: 0
    qos: 0  

switch:
# подсветка растений
  - platform: mqtt
    name: switch2
    state_topic: "home/switches/switch2/pins/12/state"
    command_topic: "home/switches/switch2/pins/12"
    payload_on: 1
    payload_off: 0
    qos: 0
# теплый пол    
  - platform: mqtt
    name: switch5
    state_topic: "home/switches/switch5/pins/14/state"
    command_topic: "home/switches/switch5/pins/14"
    payload_on: 0
    payload_off: 1
    qos: 0

# media_player:
  # platform: vlc
  # name: vlc
  # arguments: '--alsa-audio-device=default'

tts:
  platform: google
  language: 'ru'
  cache: true
  cache_dir: /tmp/tts
  time_memory: 300
  

mqtt:
  broker: rodal2807.synology.me
  port: 1883
  protocol: 3.1.1
  client_id: home-assistant
  username: !secret mqtt_login
  password: !secret mqtt_password

recorder:


# logger:
  # default: error
  # logs:
   # homeassistant.components.device_tracker: debug

dialogflow:

media_player:
  - platform: kodi
    host: 192.168.88.3
    turn_on_action:
      service: media_player.kodi_call_method
      data:
        entity_id: media_player.kodi
        method: Addons.ExecuteAddon
        addonid: script.json-cec
        params:
          command: activate
    turn_off_action:
    - service: media_player.media_stop
      data:
        entity_id: media_player.kodi
    - service: media_player.kodi_call_method
      data:
        entity_id: media_player.kodi
        method: Addons.ExecuteAddon
        addonid: script.json-cec
        params:
          command: standby