homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 123
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Moscow
  
  customize: !include customize.yaml
  
  auth_providers:
    - type: homeassistant
    # - type: legacy_api_password
    - type: trusted_networks
      trusted_networks:
        - 192.168.88.0/24

group: !include groups.yaml
script: !include scripts.yaml
automation: !include automations.yaml
intent_script: !include intent_scripts.yaml
zone: !include zones.yaml

input_datetime: !include input_datetime.yaml
input_number: !include input_number.yaml


# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

lovelace:
  mode: yaml

# Enables configuration UI
config:

default_config:

http:
  # api_password: !secret http_password
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Checks for available updates
updater:

# Discover some devices automatically
discovery:
  ignore:
  - igd

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:
  exclude:
    domains:
    - sensor

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

system_health:

#https://github.com/custom-components/custom_updater
custom_updater:
  track:
    - components
    - cards
    - python_scripts
  card_urls:
    # - https://raw.githubusercontent.com/ciotlosm/custom-lovelace/blob/master/monster-card/monster-card.js
    - https://raw.githubusercontent.com/sgttrs/lovelace-weather-card-chart/master/custom-updater.json

person:
  - name: Polina
    id: polina
    device_trackers:
      - device_tracker.phone_polina    
  - name: Alesha
    id: alesha
    device_trackers:
      - device_tracker.phone_alesha  

      
device_tracker:
  - platform: snmp
    host: 192.168.88.1
    community: !secret snmp_comunity 
    baseoid: 1.3.6.1.4.1.14988.1.1.1.2.1.1
    track_new_devices: false
    interval_seconds: 30
    consider_home: 120
  # - platform: icloud
    # username: polinaizm3004@gmail.com
    # password: !secret polina_icloud_password
    # account_name: polina_icloud
    # include_device: iPhone (Полина)
    # include_device_type: iphone
    # include_device_types:
      # - iphone
      # - ipad
    # max_interval: 10
  - platform: gpslogger
    password: !secret gpslogger_password
  # - platform: google_maps
    # username: rodal2807.home@gmail.com
    # password: !secret google_password

# Weather Prediction
weather:
  - platform: openweathermap
    api_key: !secret openweather_apikey
    mode: daily

sensor:
  - platform: time_date
    display_options:
    - 'time'
    # - 'date'
    # - 'date_time'
    # - 'time_utc'
    # - 'time_date'
    # - 'beat'
      
  - platform: yr
  
  - platform: mqtt
    state_topic: 'home/livingroom/dht'
    name: temperature
    unit_of_measurement: '°C'
    value_template: '{{ value_json.temperature }}'
    
  - platform: mqtt
    state_topic: 'home/livingroom/dht'
    name: humidity
    unit_of_measurement: '%'
    value_template: '{{ value_json.humidity }}'
        
  # - platform: filter
    # name: "filtered humidity"
    # entity_id: sensor.Humidity
    # filters:
      # - filter: outlier
        # window_size: 4
        # radius: 4.0
      # - filter: lowpass
        # time_constant: 10
        # precision: 2    

light:
# подсветка кухни
  - platform: mqtt
    name: kitchen_worktop
    state_topic: "home/kitchen/switch/worktop/state"
    command_topic: "home/kitchen/switch/worktop"
    payload_on: 1
    payload_off: 0
    qos: 0
# лампа на кухне
  - platform: mqtt
    name: kitchen_table
    state_topic: "home/kitchen/switch2/table/state"
    command_topic: "home/kitchen/switch2/table"
    payload_on: 1
    payload_off: 0
    qos: 0
# свет в ванной
  - platform: mqtt
    name: bathroom_mirror
    state_topic: "home/bathroom/switch/mirror/state"
    command_topic: "home/bathroom/switch/mirror"
    payload_on: 1
    payload_off: 0
    qos: 0  

switch:
# подсветка растений
  - platform: mqtt
    name: kitchen_plants
    state_topic: "home/kitchen/switch2/plants/state"
    command_topic: "home/kitchen/switch2/plants"
    payload_on: 1
    payload_off: 0
    qos: 0
    retain: true
# теплый пол    
  - platform: mqtt
    name: hall_warmfloor
    state_topic: "home/hall/switch/warmfloor/state"
    command_topic: "home/hall/switch/warmfloor"
    payload_on: 1
    payload_off: 0
    qos: 0
    retain: true
#автополив
  - platform: mqtt
    name: autowatering  
    state_topic: "home/kitchen/autowatering/btn1/state"
    command_topic: "home/kitchen/autowatering/btn1"
    payload_on: 28
    payload_off: 0
    qos: 0     
    
# media_player:
  # platform: vlc
  # name: vlc
  # arguments: '--alsa-audio-device=default'

tts:
  platform: google_translate
  language: 'ru'
  cache: true
  cache_dir: /tmp/tts
  time_memory: 300
  

mqtt:
  broker: rodal2807.synology.me
  port: 1883
  protocol: 3.1.1
  client_id: home-assistant
  username: !secret mqtt_login
  password: !secret mqtt_password

recorder:


# logger:
  # default: error
  # logs:
   # homeassistant.components.device_tracker: debug

dialogflow:

media_player:
  - platform: kodi
    host: 192.168.88.3
    turn_on_action:
      service: media_player.kodi_call_method
      data:
        entity_id: media_player.kodi
        method: Addons.ExecuteAddon
        addonid: script.json-cec
        params:
          command: activate
    turn_off_action:
    - service: media_player.media_stop
      data:
        entity_id: media_player.kodi
    - service: media_player.kodi_call_method
      data:
        entity_id: media_player.kodi
        method: Addons.ExecuteAddon
        addonid: script.json-cec
        params:
          command: standby
          
    
    
    
    