title: Home
resources:
    # https://github.com/ciotlosm/custom-lovelace/tree/master/monster-card
  - type: js
    url: /local/custom_ui/monster-card/monster-card.js?v=0.2.3
    
  # https://github.com/sgttrs/lovelace-weather-card-chart 
  - type: module
    url: /local/custom_ui/lovelace-weather-card-chart/custom-weather-card-chart.js?v=0.2.4
     
  # https://github.com/custom-cards/tracker-card
  - type: js
    url: /local/custom_ui/tracker-card/tracker-card.js?v=1.2.3
    
  # - url: /local/my-webfont.css
    # type: css

# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
background: center / cover no-repeat url("/background.png") fixed
# Exclude entities from "Unused entities" view
# excluded_entities:
  # - weblink.router
views:
  - title: Главная
    # Unique id for direct access /lovelace/${id}. If you don't specify one, it is added automatically.
    id: index
    background: radial-gradient(crimson, skyblue)
    theme: dark-mode
    cards:
    
      - id: main-vertical-stack-1
        type: vertical-stack
        cards:
     
          - id: main-map-filter
            type: map
            default_zoom: 14
            entities:
              - person.alesha
              - person.polina
            
          - id: main-people
            type: custom:monster-card
            card:
              type: glance
            filter:
              include:
                - domain: person     
                       
      - id: main-horizontal-stack-1
        type: horizontal-stack
        cards:
          - id: main-humidity
            type: gauge
            entity: sensor.humidity
            name: Влажность
            severity:
              red: 0
              yellow: 30
              green: 40              
          - id: main-temperature
            type: gauge
            entity: sensor.temperature
            name: Температура
            max: 50
            severity:
              normal: 0
              green: 20
              yellow: 25
              red: 30
       
      - id: main-light
        type: entities
        title: Свет
        entities:
          - light.kitchen_worktop
          - light.bathroom_mirror
          - light.kitchen_table
          
      - id: main-switches
        type: entities
        title: Выключатели
        entities:
          - switch.kitchen_plants
          - switch.hall_warmfloor
          - switch.autowatering
          
  - title: Погода
    id: weather
    icon: mdi:weather-partlycloudy
    cards:
      - id: weather-openweathermap
        type: custom:weather-card-chart
        title: Погода
        weather: weather.openweathermap
        sun: sun.sun
       
      - id: weather-windy
        type: iframe
        aspect_ratio: 100%
        url: https://embed.windy.com/embed2.html?rain,55.750,37.857,5

  - title: План
    id: plan
    icon: mdi:floor-plan
    cards:
      - type: picture-elements
        image: /local/home_plan_2d.jpg
        elements:
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.kitchen_worktop
            style:
              top: 19.5%
              left: 94%
          - type: image
            tap_action:
              action: toggle
            entity: light.kitchen_table
            state_image:
              "on": /local/lamp_on.png
              "off": /local/lamp_off.png
            style:
              top: 17%
              left: 57.5%
              width: 5%
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.bathroom_mirror
            style:
              top: 71.5%
              left: 94%              
          - type: image
            tap_action:
              action: toggle
            entity: switch.kitchen_plants
            state_image:
              "on": /local/led-light_on.png
              "off": /local/led-light_off.png
            style:
              top: 10%
              left: 54%
              width: 6%
          - type: image
            tap_action:
              action: toggle
            entity: switch.hall_warmfloor
            state_image:
              "on": /local/heater_on.png
              "off": /local/heater_off.png
            style:
              top: 92%
              left: 80%
              width: 5%
    
  - title: Настройки
    id: config
    icon: mdi:home-assistant
    cards:     
      - type: vertical-stack
        cards:
        
        # автоматизация освещения растений
        - type: markdown
          content: <h4>Атоматизация освещения растений</h4>
        - type: horizontal-stack
          cards:
          - type: entities
            entities:
              - entity: automation.turn_on_light_plants
                name: Включать утром
          - type: entities
            entities:
              - entity: input_datetime.turn_on_light_plants
                name: Время
        - type: horizontal-stack
          cards:
          - type: entities
            entities:
              - entity: automation.turn_off_light_plants
                name: Выключать вечером
          - type: entities
            entities:
              - entity: input_datetime.turn_off_light_plants
                name: Время
        
        
        # автоматизация теплого пола
        - type: markdown
          content: <h4>Автоматизация теплого пола</h4>
        - type: horizontal-stack
          cards:
          - type: entities
            entities:
              - entity: automation.turn_on_warm_flow_morning
                name: Включать утром
          - type: entities
            entities:
              - entity: input_datetime.turn_on_warm_flow_morning
                name: Время
        - type: horizontal-stack
          cards:
          - type: entities
            entities:
              - entity: automation.turn_off_warm_flow_day
                name: Выключать днем
          - type: entities
            entities:
              - entity: input_datetime.turn_off_warm_flow_day
                name: Время
              - entity: input_datetime.turn_off_warm_flow_day2
                name: Время
        - type: horizontal-stack
          cards:
          - type: entities
            entities:
              - entity: automation.turn_on_warm_flow_evening
                name: Включать вечером
          - type: entities
            entities:
              - entity: input_datetime.turn_on_warm_flow_evening
                name: Время
        - type: horizontal-stack
          cards:
          - type: entities
            entities:
              - entity: automation.turn_off_warm_flow_night
                name: Выключать на ночь
          - type: entities
            entities:
              - entity: input_datetime.turn_off_warm_flow_night
                name: Время

      - type: entities
        title: Скрипты
        entities:
          - script.icloud_update_iphone
          
      - type: custom:tracker-card
        trackers:
          - sensor.custom_card_tracker
          - sensor.custom_component_tracker
         
